export const CONFIG_ENVIRONMENT = {
  LOCAL: 'local',
  DEVELOPMENT: 'development',
  PRODUCTION: 'production',
} as const;

export const DATABASE_KEY = {
  DATABASE_URL: 'DATABASE_URL',
} as const;

export const EMAIL_KEY = {
  EMAIL_HOST: 'EMAIL_HOST',
  EMAIL_PORT: 'EMAIL_PORT',
  EMAIL_AUTH_USER: 'EMAIL_AUTH_USER',
  EMAIL_AUTH_PASSWORD: 'EMAIL_AUTH_PASSWORD',
  EMAIL_VERIFICATION_EXPIRATION_TIME: 'EMAIL_VERIFICATION_EXPIRATION_TIME',
} as const;

export const REDIS_KEY = {
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  REDIS_PASSWORD: 'REDIS_PASSWORD',
} as const;

export const JWT_KEY = {
  JWT_ACCESS_TOKEN_SECRET: 'JWT_ACCESS_TOKEN_SECRET',
  JWT_REFRESH_TOKEN_SECRET: 'JWT_REFRESH_TOKEN_SECRET',
  JWT_ACCESS_TOKEN_EXPIRATION_TIME: 'JWT_ACCESS_TOKEN_EXPIRATION_TIME',
  JWT_REFRESH_TOKEN_EXPIRATION_TIME: 'JWT_REFRESH_TOKEN_EXPIRATION_TIME',
} as const;

export const AWS_S3_KEY = {
  S3_ACCESS_KEY: 'S3_ACCESS_KEY',
  S3_SECRET_KEY: 'S3_SECRET_KEY',
  S3_BUCKET_REGION: 'S3_BUCKET_REGION',
  S3_BUCKET_NAME: 'S3_BUCKET_NAME',
} as const;

export const ENVIRONMENT_KEY = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  ...EMAIL_KEY,
  ...REDIS_KEY,
  ...JWT_KEY,
  ...AWS_S3_KEY,
} as const;
