name: Deploy

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  cicd:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.18.2

      - name: Install Backend-Server
        run: npm ci

      - name: Compile Backend-Server
        run: npm run build

   
